# Generated by Django 5.0.2 on 2025-04-20 05:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jitsi/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='jitsi/favicons/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='jitsi/backgrounds/')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='jitsi/watermarks/')),
                ('primary_color', models.CharField(default='#0056E0', max_length=7)),
                ('secondary_color', models.CharField(default='#17A0DB', max_length=7)),
                ('background_color', models.CharField(default='#040404', max_length=7)),
                ('show_footer', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('custom_js', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JitsiFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('enable_audio', models.BooleanField(default=True)),
                ('enable_video', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_screen_sharing', models.BooleanField(default=True)),
                ('enable_recording', models.BooleanField(default=False)),
                ('enable_livestreaming', models.BooleanField(default=False)),
                ('enable_breakout_rooms', models.BooleanField(default=False)),
                ('enable_lobby', models.BooleanField(default=False)),
                ('enable_end_to_end_encryption', models.BooleanField(default=False)),
                ('enable_password_protection', models.BooleanField(default=False)),
                ('enable_reactions', models.BooleanField(default=True)),
                ('enable_raise_hand', models.BooleanField(default=True)),
                ('enable_tile_view', models.BooleanField(default=True)),
                ('enable_filmstrip', models.BooleanField(default=True)),
                ('enable_polls', models.BooleanField(default=False)),
                ('enable_whiteboard', models.BooleanField(default=False)),
                ('enable_blur_background', models.BooleanField(default=True)),
                ('additional_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JitsiRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('moderator_password', models.CharField(blank=True, max_length=50, null=True)),
                ('attendee_password', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='JitsiParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('attendee', 'Attendee'), ('guest', 'Guest')], default='attendee', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jitsi.jitsiroom')),
            ],
        ),
        migrations.CreateModel(
            name='JitsiMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jitsi.jitsicustomization')),
                ('feature_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jitsi.jitsifeatureconfig')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='jitsi.jitsiroom')),
            ],
        ),
    ]
