# Generated by Django 5.0.2 on 2025-04-20 06:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jitsicustomization',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/jitsi/', location='/Users/abhishek/unlock/kabhishek2025/media_files/jitsi'), upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='jitsicustomization',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/jitsi/', location='/Users/abhishek/unlock/kabhishek2025/media_files/jitsi'), upload_to='favicons/'),
        ),
        migrations.AlterField(
            model_name='jitsicustomization',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/jitsi/', location='/Users/abhishek/unlock/kabhishek2025/media_files/jitsi'), upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='jitsicustomization',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/jitsi/', location='/Users/abhishek/unlock/kabhishek2025/media_files/jitsi'), upload_to='watermarks/'),
        ),
    ]
