# Generated by Django 5.0.2 on 2025-04-19 18:35

import pagebuilder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='template_name',
            field=models.CharField(blank=True, choices=pagebuilder.models.get_available_templates, help_text='Select which template to use if type is template', max_length=100, verbose_name='Template Name'),
        ),
    ]
