# Generated by Django 5.0.2 on 2025-04-19 18:00

import django.db.models.deletion
import media.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media.mediafolder', verbose_name='Parent Folder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
                'ordering': ['name'],
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to=media.models.get_upload_path, verbose_name='File')),
                ('file_name', models.CharField(editable=False, max_length=255, verbose_name='File Name')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='File Size')),
                ('file_type', models.CharField(editable=False, max_length=100, verbose_name='File Type')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='Media Type')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='media.mediafolder', verbose_name='Folder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
